name: CI/CD to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      # Build & Push Backend
      - name: Build Backend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest

      # Build & Push Frontend
      - name: Build Frontend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest

      # Deploy Backend
      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: todo-backendhai
          images: ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest

      # Deploy Frontend
      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: todo-frontendhai
          images: ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
